[tools]
# Latest versions of each tool
bun = 'latest'
go = 'latest'
node = 'lts'

[settings]
# Always keep the downloaded archives for faster reinstalls
always_keep_download = true

# Enable experimental features
experimental = true

# Configure status display
[settings.status]
show_env = true
show_tools = true
